### PR TITLE
Gracefully shutdown of the websocket client

### LINKED ISSUE #163: wsclient: Unexpected error while receiving:read ... use of closed network connection
When ws client is stopped, it closes the connection here  https://github.com/open-telemetry/opamp-go/blob/06011e4b754e9d41cbba7b5c166c6d2eec7b82d8/client/wsclient.go#L84-L90 and cancels the context https://github.com/open-telemetry/opamp-go/blob/06011e4b754e9d41cbba7b5c166c6d2eec7b82d8/client/internal/clientcommon.go#L151-L156 And the [ReceiverLoop](https://github.com/open-telemetry/opamp-go/blob/06011e4b754e9d41cbba7b5c166c6d2eec7b82d8/client/internal/wsreceiver.go#L45) tries to read a message from the closed connection resulting in an error.
```
Unexpected error while receiving: read tcp 127.0.0.1:53775->127.0.0.1:53774: use of closed network connection
```

### PR DESCRIPTION
**Pull request by haoqixu**
Resolves #163

### CODE REVIEW

**Comment by haoqixu** [comment]
Could you please take a look @evan-bradley @srikanthccv @tigrannajaryan

**Comment by haoqixu** [comment]
I have watched the meeting record and I think I can add some explanation about this PR.

The solution here is making `wsclient.runOneCycle` responsible for the entire lifecyle of the connection and controlling the running of sender and receiver. It also move the receiver to run in a separate goroutine. `wsclient.runOneCycle` will ensure that both sender and receiver are stopped and the connection is closed before it returns. So we don't need to care about the connection outside `wsclient.runOneCycle`.

When the client is shutting down, the `sender` goroutine will be cancelled by the ctx, send the close message to server and return the error to `wsclient.runOneCycle` via sender.Err(). `wsclient.runOneCycle` will wait for the close message from server until timeout and ensure the connection is closed.

If the server wants to close the connection, it should send the close message to initiate the close handshake. When a close message is received, the connection read methods will handle it by calling the close handler (the default handler will send a close message back to the peer. I think this is what we want.) and return a CloseError. The receiver loop will stop on any error. `wsclient.runOneCycle` will stop the sender and close the connection when receiver is stopped.

File: client/wsclient.go [hunk 1]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
-	procCancel()
-
-	// If we exited receiverLoop it means there is a connection error, we cannot
-	// read messages anymore. We need to start over.
+	r.Start(ctx)
+
+	select {
+	case <-c.sender.IsStopped():
+		// sender will send close message to initiate the close handshake
+		if err := c.sender.Err(); err != nil && err != websocket.ErrCloseSent {
```
Comment (srikanthccv) [inline client/wsclient.go:258]: Is this `err != websocket.ErrCloseSent` to handle the case when the server initiates the close?

File: client/internal/wssender.go [hunk 2]
```diff
@@ -56,13 +66,22 @@ out:
 			s.sendNextMessage()
 
 		case <-ctx.Done():
+			s.err = s.sendCloseMessage()
```
Comment (srikanthccv) [inline client/internal/wssender.go:69]: This means stopping the sender also closes the connection which might be unexpected because run should simply run until the context is cancelled but it also closes the connection. I think sending Close message should be part of client `Stop`.

Comment (haoqixu) [reply client/internal/wssender.go:69]: This is by design. Stopping the sender would always try to send the close message for the close handshake and `runOneCycle` is responsible for the subsequent steps of connection closing. I updated the comment of the `runOneCycle()`.

File: client/wsclient.go (hunk 1 above)
Comment (haoqixu) [reply client/wsclient.go:258]: Yes. The sender and receiver run concurrently. There is a possibility that the server and client initiate the closing handshake at the same time. In this case, the close message may be sent by CloseHandler, which is called in the receiver.

File: client/wsclient.go [hunk 3]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+			c.common.Logger.Debugf("failed to send close message, close without the handshake.")
+			break
+		}
 
-	// Close the connection to unblock the WSSender as well.
-	_ = c.conn.Close()
+		c.common.Logger.Debugf("waiting for close message from server.")
+		select {
+		case <-r.IsStopped():
+			c.common.Logger.Debugf("shutdown handshake complete.")
```
[the remark this answers is not in the document]
Comment (haoqixu) [reply client/wsclient.go:266]: I think the receiver loop has handled it and printed a log for it. However, the log message here is not very accurate. The "complete" here actually means that the receiver loop has also exited. 🤔

**Review by srikanthccv — COMMENTED** [review]
Overall LGTM, One main difference from this PR https://github.com/open-telemetry/opamp-go/pull/205 is that the sender initiates the close handshake which makes the implementation a little simpler but also the connection management is now done b/w wsclient and wssender. @evan-bradley what do you think?

File: client/wsclient.go [hunk 4]
```diff
@@ -199,19 +199,25 @@ func (c *wsClient) ensureConnected(ctx context.Context) error {
 // runOneCycle performs the following actions:
 //  1. connect (try until succeeds).
 //  2. send first status report.
-//  3. receive and process messages until error happens.
+//  3. start the sender to wait for scheduled message and send it to the server.
+//  4. start the receiver to receive and process messages until error happens.
+//  5. wait until both sender and receiver are stopped.
```
Comment (evan-bradley) [inline client/wsclient.go:204]:
```suggestion
//  3. start the sender to wait for scheduled messages and send them to the server.
//  4. start the receiver to receive and process messages until an error happens.
//  5. wait until both the sender and receiver are stopped.
```
Grammar nits.

File: client/wsclient.go [hunk 5]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+			<-r.IsStopped()
+		}
+	case <-r.IsStopped():
+		// If we exited receiverLoop it means there is a connection error, we cannot
+		// read messages anymore. We need to start over.
 
-	// Wait for WSSender to stop.
-	c.sender.WaitToStop()
+		stopSender()
+		<-c.sender.IsStopped()
```
Comment (evan-bradley) [inline client/wsclient.go:278]: Running `stopSender` will attempt to send a message to the server. Do you know whether this will time out in a reasonable timeframe, or should we race this with `c.connShutdownTimeout` to ensure it doesn't hang?

**Review by evan-bradley — COMMENTED** [review]
Thanks for doing this, overall it looks good to me. I think this approach is an improvement over https://github.com/open-telemetry/opamp-go/pull/205. There may additional improvements we can make in the future, but for now this will resolve the errors we are seeing and will cleanly close the connection.

File: client/wsclient.go (hunk 5 above)
Comment (haoqixu) [reply client/wsclient.go:278]: `c.connShutdownTimeout` is controlling how long the wsclient will wait for the ACK from server, and the timeout for sendding the close message to the server is [`defaultSendCloseMessageTimeout`](https://github.com/open-telemetry/opamp-go/pull/213/files#diff-1a7764ac131862565b9f9783634aa0c05d383cc44c34268308865908e1c3d02dR16)(5s). So it will not hang here.

`c.connShutdownTimeout` is currently only modified during testing and both of them are not configurable for now. We can improve the Client API to make them configurable later.

**Review by srikanthccv — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]

File: client/wsclient.go (hunk 1 above)
Comment (tigrannajaryan) [reply client/wsclient.go:258]: Can we change `sender.Err()` to return nil if the error was `websocket.ErrCloseSent`? Let's consider it an internal implementation detail of the sender and avoid leaking it here. That we only need to check `err` for nil here. Sender seeing a `websocket.ErrCloseSent` response is a success, we don't need to consider it an error.

File: client/wsclient.go [hunk 6]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
-
-	// If we exited receiverLoop it means there is a connection error, we cannot
-	// read messages anymore. We need to start over.
+	r.Start(ctx)
+
+	select {
+	case <-c.sender.IsStopped():
+		// sender will send close message to initiate the close handshake
+		if err := c.sender.Err(); err != nil && err != websocket.ErrCloseSent {
+			c.common.Logger.Debugf("failed to send close message, close without the handshake.")
```
Comment (tigrannajaryan) [inline client/wsclient.go:259]: Should we include `err` in the log?

File: client/wsclient.go [hunk 7]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+			break
+		}
 
-	// Close the connection to unblock the WSSender as well.
-	_ = c.conn.Close()
+		c.common.Logger.Debugf("waiting for close message from server.")
```
Comment (tigrannajaryan) [inline client/wsclient.go:263]:
```suggestion
		c.common.Logger.Debugf("Waiting for receiver to stop.")
```
I think receiver waiting for close message is a implementation detail from our perspective. Let's not leak implementation detail. If we want this exact log message then better to move it inside receiver.

File: client/wsclient.go (hunk 6 above)
Comment (tigrannajaryan) [inline client/wsclient.go:259]:
```suggestion
			c.common.Logger.Debugf("Error stopping the sender: %v", err)
```

File: client/wsclient.go (hunk 3 above)
Comment (tigrannajaryan) [inline client/wsclient.go:266]:
```suggestion
			c.common.Logger.Debugf(Receiver stopped.")
```

File: client/wsclient.go [hunk 8]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+		select {
+		case <-r.IsStopped():
+			c.common.Logger.Debugf("shutdown handshake complete.")
+		case <-time.After(c.connShutdownTimeout):
+			c.common.Logger.Debugf("timeout waiting for close message.")
```
Comment (tigrannajaryan) [inline client/wsclient.go:268]:
```suggestion
			c.common.Logger.Debugf("Timeout waiting for receiver to stop.")
```

File: client/wsclient.go [hunk 9]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+			// not receive close message from the server, close the connection to force the receive loop to stop
```
Comment (tigrannajaryan) [inline client/wsclient.go:269]:
```suggestion
			// Close the connection to force the receive loop to stop.
```

File: client/wsclient.go [hunk 10]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+			_ = c.conn.Close()
+			<-r.IsStopped()
```
Comment (tigrannajaryan) [inline client/wsclient.go:271]: Can this potentially block forever? To be defensive we probably need to have a timeout here.

File: client/wsclient.go (hunk 5 above)
Comment (tigrannajaryan) [inline client/wsclient.go:278]: Does this waiting require a timeout?

Comment (haoqixu) [reply client/wsclient.go:278]: I don't think it's necessary, as mentioned above(https://github.com/open-telemetry/opamp-go/pull/213/files#r1446914020)

File: client/wsclient.go (hunk 10 above)
Comment (haoqixu) [reply client/wsclient.go:271]: Receiver is waiting to read data from the connection (via `ReadMessage`), I think closing the connection is enough to unblock the `ReadMessage`. 🤔

File: client/internal/wssender.go [hunk 11]
```diff
@@ -56,13 +66,22 @@ out:
...
 	}
 
 	close(s.stopped)
 }
 
+func (s *WSSender) sendCloseMessage() error {
+	return s.conn.WriteControl(
+		websocket.CloseMessage,
+		websocket.FormatCloseMessage(websocket.CloseNormalClosure, "Normal closure"),
+		time.Now().Add(defaultSendCloseMessageTimeout),
```
[the remark this answers is not in the document]
Comment (tigrannajaryan) [reply client/internal/wssender.go:85]: My understanding is that flushing data to a socket can take indefinitely long if the peer is not responsive. It is unfortunately there is no cancellation possible for this call.

File: client/wsclient.go (hunk 5 above)
Comment (tigrannajaryan) [reply client/wsclient.go:278]: I am not sure about it. 

Calling `stopSender()` here triggers context cancellation. That in turn causes the `sender` to call `sendCloseMessage()`. `sendCloseMessage()` can be blocked indefinitely if the peer server is not reading from the socket and there is no room in the local socket buffer. This means the `sender` will never be stopped and `IsStopped()` channel will never be closed. We can block indefinitely long here.

I think we need a timeout here and need to close the connection forcedly like we do it to force the receiver to stop above in line 270.

I may be missing something here. Please help me with the analysis.

File: client/internal/wsreceiver.go [hunk 12]
```diff
@@ -36,14 +40,31 @@ func NewWSReceiver(
...
+	go r.ReceiverLoop(ctx)
+}
+
+// IsStopped returns a channel that's closed when the receiver is stopped.
+func (r *wsReceiver) IsStopped() <-chan struct{} {
+	return r.stopped
+}
+
+// Err returns the error that caused the receiver loop to exit.
+func (r *wsReceiver) Err() error {
```
Comment (tigrannajaryan) [inline client/internal/wsreceiver.go:60]: I cannot see this function used anywhere anymore. If it is not used please delete and also delete `r.err` field from the struct.

File: client/internal/wssender.go [hunk 13]
```diff
@@ -37,15 +44,20 @@ func (s *WSSender) Start(ctx context.Context, conn *websocket.Conn) error {
...
-// that was passed to Start().
-func (s *WSSender) WaitToStop() {
-	<-s.stopped
+// IsStopped returns a channel that's closed when the sender is stopped.
+func (s *WSSender) IsStopped() <-chan struct{} {
+	return s.stopped
+}
+
+// Err returns the error of sending close message.
+func (s *WSSender) Err() error {
```
Comment (tigrannajaryan) [inline client/internal/wssender.go:59]:
```suggestion
func (s *WSSender) StoppingErr() error {
```

File: client/internal/wssender.go [hunk 14]
```diff
@@ -37,15 +44,20 @@ func (s *WSSender) Start(ctx context.Context, conn *websocket.Conn) error {
...
-// WaitToStop blocks until the sender is stopped. To stop the sender cancel the context
-// that was passed to Start().
-func (s *WSSender) WaitToStop() {
-	<-s.stopped
+// IsStopped returns a channel that's closed when the sender is stopped.
+func (s *WSSender) IsStopped() <-chan struct{} {
+	return s.stopped
+}
+
+// Err returns the error of sending close message.
```
Comment (tigrannajaryan) [inline client/internal/wssender.go:58]:
```suggestion
// StoppingErr returns an error if there was a problem with stopping the sender.
// If stopping was successful will return nil.
// StoppingErr() can be called only after IsStopped() is signalled.
```

File: client/wsclient.go [hunk 15]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
-	procCancel()
-
-	// If we exited receiverLoop it means there is a connection error, we cannot
-	// read messages anymore. We need to start over.
+	r.Start(ctx)
+
+	select {
+	case <-c.sender.IsStopped():
+		// sender will send close message to initiate the close handshake
+		if err := c.sender.Err(); err != nil {
```
Comment (tigrannajaryan) [inline client/wsclient.go:258]:
```suggestion
		if err := c.sender.StoppingErr(); err != nil {
```

File: client/wsclient.go [hunk 16]
```diff
@@ -245,19 +250,33 @@ func (c *wsClient) runOneCycle(ctx context.Context) {
...
+			c.common.Logger.Debugf("Error stopping the sender: %v", err)
+			break
```
Comment (tigrannajaryan) [inline client/wsclient.go:260]: Is there a reason we `break` here? If the sender stopping failed shouldn't we still try to stop the receiver and close the connection?

**Review by tigrannajaryan — COMMENTED** [review]
Thanks for your patience @haoqixu 

Please bear with me while I am trying to understand all the concurrent flows.

File: client/wsclient.go (hunk 5 above)
Comment (tigrannajaryan) [reply client/wsclient.go:278]: OK, from the comment thread `sendCloseMessage()` will not blocked indefinitely, it will return at most after `defaultSendCloseMessageTimeout` so this does not need a timeout.

File: client/wsclient.go (hunk 16 above)
Comment (haoqixu) [reply client/wsclient.go:264]: I think this `break` was introduced during the updates of the PR. The initial code does not wait for the receiver to stop, leaving the closing of the connection to the defer. I update the branch to close the conneciton explicitly and wait for the receiver to stop before break.

**Comment by tigrannajaryan** [comment]
Thanks for updates @haoqixu 
The PR mostly looks good to me, the only remaining question is https://github.com/open-telemetry/opamp-go/pull/213/files#r1462064174

**Comment by haoqixu** [comment]
> The PR mostly looks good to me, the only remaining question is https://github.com/open-telemetry/opamp-go/pull/213/files#r1462064174

I have updated the PR with https://github.com/open-telemetry/opamp-go/pull/213/commits/5fa47a3bfe0212121d1031031dcda2362ba094b1

**Comment by tigrannajaryan** [comment]
@haoqixu this looks good to me. Can you please resolve the conflicts?

**Comment by haoqixu** [comment]
#240 puts the `receiveMessage` into a separate goroutine.

**Comment by haoqixu** [comment]
By design, we need to canceling the context and closing the connection to stop the `ReceiverLoop`.  And the gracefully shutdown flow of `wsclient` will do this for us. Considering `ReceiverLoop` as an internal implementation detail of the `wsclient`, we could just gracefully shut down the `wsclient`.

`gorilla/websocket` doesn't provide a method to unblock the reading of connection and we always need to close the connection to unblock the reading.

#240 puts the reading of connections into a separate goroutine, which is unnecessary and may cause goroutine leaks. And the update here actually reverts #240

**Comment by haoqixu** [comment]
please take a look. @tigrannajaryan

**Comment by tigrannajaryan** [comment]
> By design, we need to canceling the context and closing the connection to stop the `ReceiverLoop`. And the gracefully shutdown flow of `wsclient` will do this for us. Considering `ReceiverLoop` as an internal implementation detail of the `wsclient`, we could just gracefully shut down the `wsclient`.
> 
> `gorilla/websocket` doesn't provide a method to unblock the reading of connection and we always need to close the connection to unblock the reading.
> 
> #240 puts the reading of connections into a separate goroutine, which is unnecessary and may cause goroutine leaks. And the update here actually reverts #240

@srikanthccv please take another look at this PR since it reverts your earlier PR #240.

**Comment by srikanthccv** [comment]
We don't make it clear anywhere that `ReceiverLoop` is an internal implementation detail. By making both connection closing and context cancellation (I don't see any use of context in this case) mandatory for exiting the receiver loop we may prematurely close the connection. There would be leaks if `wsReceiver` were to work in isolation but given we will close the connection followed by the receiver loop exit, there shouldn't be goroutine leaks? 

We will need to send a final message(s) such as agent disconnect (not implemented yet) before stopping the client. I'd prefer to see `wsclient` have final say in when to close for such kind of reasons. I want to hear your thoughts on this.

**Comment by srikanthccv** [comment]
I recall we had discussed this already once. The implementation can always evolve to satisfy the needs but We should explicitly call out what we consider as internal implementation details.

**Comment by tigrannajaryan** [comment]
I agree it is more idiomatic to honor the cancellation in ReceiverLoop. I am not sure wha the problem is with the leak. If there is one let's fix it, otherwise we I think we don't need to worry about hypotheticals in this particular case.

**Comment by srikanthccv** [comment]
I am not sure I follow the simplicity part. I don't see much benefit of one over the other. Regarding the memory leak concern - as we are going to gracefully close the connection with this change there should not be any go routine leak or did I miss something?

**Comment by haoqixu** [comment]
I have updated the code. Please take another look.

**Comment by jaronoff97** [comment]
@tigrannajaryan are we good to merge this? I just ran into an instance of this in the opampextension

**Comment by tigrannajaryan** [comment]
Thank you @haoqixu
